# Generated by Django 5.2.5 on 2026-09-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_add_flight_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskaccount',
            name='manager_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='담당자 전화번호'),
        ),
        migrations.AddField(
            model_name='kioskaccount',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='별명'),
        ),
        migrations.AddField(
            model_name='kioskaccount',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='기관명'),
        ),
    ]
