import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { ChickenMenuItem } from "./ChickenStoreDetailScreen";

export function ChickenMenuOptionScreen({ menu, onBack, onAdd }: { menu: ChickenMenuItem; onBack: () => void; onAdd: () => void }) {
  const price = Number(menu.price.replace(/[^0-9]/g, ""));
  return <View style={s.page}>
    <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
      <View style={s.hero}><Image source={menu.image} style={s.image} /><View style={s.heroTop}><Pressable accessibilityRole="button" accessibilityLabel="메뉴 목록으로 돌아가기" onPress={onBack}><Text style={s.back}>‹</Text></Pressable><Text style={s.icon}>⌕  🛒</Text></View></View>
      <View style={s.main}><Text style={s.rank}>{menu.badge}</Text><Text style={s.name}>{menu.name}</Text><Text style={s.desc}>{menu.description}</Text><Text style={s.review}>메뉴 리뷰 {menu.id === "fried" ? "218" : "97"}개  ›</Text><View style={s.priceRow}><Text style={s.priceLabel}>가격</Text><Text style={s.price}>{menu.price}</Text></View></View>
      <View style={s.divider}/><View style={s.optionHead}><Text style={s.optionTitle}>치킨 조각 선택</Text><Text style={s.required}>필수</Text></View>
      {["뼈 있는 치킨", "순살 치킨 (+2,000원)"].map((item, index) => <View key={item} style={s.option}><View style={[s.radio, index === 0 && s.radioOn]}>{index === 0 ? <View style={s.dot}/> : null}</View><Text style={s.optionText}>{item}</Text>{index === 0 ? <Text style={s.popular}>많이 골라요</Text> : null}</View>)}
      <View style={s.divider}/><View style={s.optionHead}><Text style={s.optionTitle}>사이드 추가</Text><Text style={s.optional}>선택</Text></View>
      {["치즈볼 3개 (+3,000원)", "콜라 500ml (+2,000원)"].map((item) => <View key={item} style={s.option}><View style={s.radio}/><Text style={s.optionText}>{item}</Text></View>)}
    </ScrollView>
    <View style={s.bottom}><View><Text style={s.minimum}>배달 최소주문금액 12,000원</Text><Text style={s.total}>{price.toLocaleString()}원</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`${menu.name} 장바구니에 담기`} style={s.add} onPress={onAdd}><Text style={s.addText}>{price.toLocaleString()}원 담기</Text></Pressable></View>
  </View>;
}
const s=StyleSheet.create({page:{flex:1,width:"100%",maxWidth:680,backgroundColor:"white"},content:{paddingBottom:105},hero:{height:245,backgroundColor:"#eee"},image:{width:"100%",height:"100%",resizeMode:"cover"},heroTop:{position:"absolute",top:12,left:18,right:18,flexDirection:"row",justifyContent:"space-between"},back:{fontSize:48,color:"white",lineHeight:48},icon:{fontSize:25,color:"white",fontWeight:"900"},main:{padding:20},rank:{alignSelf:"flex-start",backgroundColor:"#f3f4f5",paddingHorizontal:8,paddingVertical:5,borderRadius:6,fontWeight:"900",color:"#555"},name:{marginTop:13,fontSize:29,fontWeight:"900"},desc:{marginTop:16,fontSize:18,lineHeight:28,color:"#777"},review:{marginTop:22,fontWeight:"900",fontSize:18},priceRow:{marginTop:36,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},priceLabel:{fontSize:23,fontWeight:"900"},price:{fontSize:26,fontWeight:"900"},divider:{height:10,backgroundColor:"#f3f4f5"},optionHead:{padding:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},optionTitle:{fontSize:23,fontWeight:"900"},required:{backgroundColor:"#151515",color:"white",borderRadius:18,paddingHorizontal:11,paddingVertical:7,fontWeight:"900"},optional:{backgroundColor:"#f1f2f3",borderRadius:18,paddingHorizontal:11,paddingVertical:7,color:"#666",fontWeight:"900"},option:{paddingHorizontal:20,paddingBottom:25,flexDirection:"row",alignItems:"center"},radio:{width:30,height:30,borderRadius:15,borderWidth:2,borderColor:"#d6d9dc",alignItems:"center",justifyContent:"center"},radioOn:{borderColor:"#171717",backgroundColor:"#171717"},dot:{width:10,height:10,borderRadius:5,backgroundColor:"white"},optionText:{fontSize:18,marginLeft:14,fontWeight:"700"},popular:{marginLeft:"auto",color:"#1976ec",fontWeight:"900"},bottom:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"white",borderTopWidth:1,borderColor:"#eee",padding:14,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},minimum:{fontSize:12,color:"#777"},total:{fontSize:23,fontWeight:"900",marginTop:4},add:{backgroundColor:"#16daca",paddingHorizontal:25,paddingVertical:18,borderRadius:14},addText:{fontSize:18,fontWeight:"900"}});
