import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

export function DeliveryPaymentScreen({ total, onBack, onPay }: { total: number; onBack: () => void; onPay: () => void }) {
  const paymentTotal = Math.max(total - 3000, 0);
  return <View style={s.page}><ScrollView contentContainerStyle={s.content}>
    <View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>주문하기</Text><View style={{ width: 38 }} /></View>
    <View style={s.card}><View style={s.row}><Text style={s.cardTitle}>할인쿠폰</Text><Text style={s.sub}>2개 보유</Text></View><View style={s.coupon}><Text style={s.couponText}><Text style={s.purple}>3,000원</Text> 할인 적용됨</Text><Text style={s.arrow}>›</Text></View><View style={s.rule}/><View style={s.row}><Text style={s.label}>선물함</Text><Text style={s.sub}>0원  ›</Text></View><View style={s.rule}/><View style={s.row}><Text style={s.label}>포인트 ⓘ</Text><Text style={s.sub}>0원</Text></View></View>
    <View style={s.card}><Text style={s.cardTitle}>결제수단</Text><Method title="배민페이머니" detail="최대 125원 적립"/><View style={s.info}><Text style={s.coin}>P</Text><Text style={s.infoText}>배민페이머니로 결제하면{`\n`}배민포인트 <Text style={s.purple}>0.5% 적립</Text>해드려요!</Text></View><Method title="신용·체크카드"/><Method title="토스페이"/><Method title="카카오페이" selected/><Method title="기타 결제수단"/></View>
    <View style={s.card}><View style={s.row}><Text style={s.cardTitle}>결제 금액</Text><Text style={s.price}>{paymentTotal.toLocaleString()}원</Text></View><View style={s.amountRow}><Text style={s.amountLabel}>메뉴금액</Text><Text style={s.amount}>{total.toLocaleString()}원</Text></View><View style={s.amountRow}><Text style={s.amountLabel}>배달팁</Text><Text style={s.amount}>0원</Text></View><View style={s.dash}/><View style={s.amountRow}><Text style={s.purple}>총 할인받은 금액</Text><Text style={s.purple}>-3,000원</Text></View><Text style={s.note}>⚡ 3,000원 할인이 적용됐어요</Text></View>
  </ScrollView><View style={s.bottom}><View><Text style={s.bottomDiscount}>⚡ 3,000원{`\n`}할인이 적용됐어요</Text></View><Pressable accessibilityRole="button" accessibilityLabel="연습 결제 완료하기" style={s.pay} onPress={onPay}><Text style={s.payText}>{paymentTotal.toLocaleString()}원 결제하기</Text></Pressable></View></View>;
}
function Method({title,detail,selected=false}:{title:string;detail?:string;selected?:boolean}) { return <Pressable style={s.method}><View style={[s.radio,selected&&s.radioOn]}>{selected&&<View style={s.dot}/>}</View><Text style={s.methodText}>{title}</Text>{detail&&<Text style={s.detail}>{detail}</Text>}</Pressable> }
const s=StyleSheet.create({page:{flex:1,width:"100%",maxWidth:680,backgroundColor:"#f3f5f6"},content:{paddingBottom:110},header:{height:78,backgroundColor:"white",paddingHorizontal:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:46,lineHeight:46},title:{fontSize:25,fontWeight:"900"},card:{margin:18,marginBottom:0,padding:20,borderRadius:20,backgroundColor:"white"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},cardTitle:{fontSize:22,fontWeight:"900"},label:{fontSize:19,fontWeight:"800"},sub:{fontSize:17},coupon:{borderWidth:1,borderColor:"#d7d9dd",borderRadius:14,padding:18,marginTop:20,flexDirection:"row",justifyContent:"space-between"},couponText:{fontSize:20,fontWeight:"800"},arrow:{fontSize:32,lineHeight:24},purple:{color:"#4b31ed",fontWeight:"900"},rule:{height:1,backgroundColor:"#eee",marginVertical:19},method:{flexDirection:"row",alignItems:"center",paddingTop:22},radio:{width:32,height:32,borderRadius:16,borderWidth:2,borderColor:"#d8dadd",alignItems:"center",justifyContent:"center"},radioOn:{backgroundColor:"#151515",borderColor:"#151515"},dot:{width:11,height:11,borderRadius:6,backgroundColor:"white"},methodText:{fontSize:20,marginLeft:14},detail:{marginLeft:10,color:"#4b31ed",fontWeight:"900",backgroundColor:"#eef0ff",padding:5,borderRadius:5},info:{marginTop:15,padding:16,borderRadius:18,backgroundColor:"#eef0ff",flexDirection:"row",alignItems:"center"},coin:{width:46,height:46,borderRadius:23,backgroundColor:"#f4bd24",textAlign:"center",textAlignVertical:"center",fontWeight:"900",fontSize:24},infoText:{marginLeft:13,fontSize:15,lineHeight:23,fontWeight:"700"},price:{fontSize:24,fontWeight:"900"},amountRow:{marginTop:17,flexDirection:"row",justifyContent:"space-between"},amountLabel:{fontSize:17},amount:{fontSize:17,fontWeight:"700"},dash:{borderTopWidth:1,borderStyle:"dashed",borderColor:"#d3d5d8",marginVertical:20},note:{marginTop:20,padding:16,borderRadius:14,backgroundColor:"#eff0ff",color:"#4b31ed",fontSize:16,fontWeight:"900",textAlign:"center"},bottom:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"white",padding:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},bottomDiscount:{color:"#4b31ed",fontWeight:"900",lineHeight:21},pay:{backgroundColor:"#16daca",paddingVertical:18,paddingHorizontal:22,borderRadius:14},payText:{fontSize:18,fontWeight:"900"}});
