import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { DeliveryAddress } from "../types";
import type { ChickenMenuItem } from "./ChickenStoreDetailScreen";

export function DeliveryOrderScreen({ address, items, total, onBack, onPay }: { address: DeliveryAddress; items: ChickenMenuItem[]; total: number; onBack: () => void; onPay: () => void }) {
  return <View style={s.page}><ScrollView contentContainerStyle={s.content}><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="가게로 돌아가기" onPress={onBack}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>주문하기</Text><View style={s.headerSpacer}/></View><View style={s.delivery}><Text style={s.deliveryTitle}>한집배달로 받을게요</Text><Text style={s.time}>◷ 10~20분 후 도착</Text></View><View style={s.card}><Text style={s.cardTitle}>담은 메뉴 {items.length}개</Text>{items.map((item) => <Menu key={item.id} item={item}/>)}</View><View style={s.card}><Text style={s.cardTitle}>배달주소</Text><Text style={s.address}>⌖ {address.name}</Text><Text style={s.addressSub}>{address.roadAddress}</Text><View style={s.line}/><Text style={s.cardTitle}>라이더 요청사항</Text><Text style={s.request}>문 앞에 두고 노크해 주세요.  ›</Text></View><View style={s.card}><Text style={s.cardTitle}>내 연락처</Text><Text style={s.request}>010-7760-3582  ›</Text></View></ScrollView><View style={s.bottom}><View><Text style={s.discount}>첫 주문 3,000원 할인</Text><Text style={s.total}>{total.toLocaleString()}원</Text></View><Pressable accessibilityRole="button" accessibilityLabel="주문 내용 확인하고 결제로 이동" style={s.pay} onPress={onPay}><Text style={s.payText}>{total.toLocaleString()}원 주문하기</Text></Pressable></View></View>;
}
function Menu({ item }: { item: ChickenMenuItem }) { return <View style={s.menu}><Image source={item.image} style={s.menuImage}/><View style={s.menuCopy}><Text style={s.menuName}>{item.name} 1개</Text><Text style={s.menuPrice}>{item.price}</Text><Text style={s.menuSub}>기본 옵션</Text></View><Text style={s.quantity}>−  1  ＋</Text></View>; }
const s=StyleSheet.create({page:{flex:1,width:"100%",maxWidth:680,backgroundColor:"#f3f5f6"},content:{paddingBottom:115},header:{height:75,paddingHorizontal:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between",backgroundColor:"white"},headerSpacer:{width:38},back:{fontSize:46,lineHeight:46},title:{fontSize:25,fontWeight:"900"},delivery:{padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},deliveryTitle:{fontSize:20,fontWeight:"900"},time:{fontSize:16},card:{backgroundColor:"white",borderRadius:20,marginHorizontal:18,marginBottom:14,padding:20},cardTitle:{fontSize:21,fontWeight:"900",marginBottom:17},menu:{flexDirection:"row",alignItems:"center",marginBottom:18},menuImage:{width:72,height:72,borderRadius:12,marginRight:15},menuCopy:{flex:1},menuName:{fontWeight:"900",fontSize:17},menuPrice:{fontSize:18,fontWeight:"900",marginTop:7},menuSub:{color:"#888",marginTop:3},quantity:{fontWeight:"900",fontSize:16},address:{fontWeight:"900",fontSize:18,lineHeight:27},addressSub:{color:"#888",fontSize:16,marginTop:4},line:{height:1,backgroundColor:"#eee",marginVertical:20},request:{fontSize:17},bottom:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"white",padding:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},discount:{color:"#5333ee",fontWeight:"900"},total:{fontSize:23,fontWeight:"900",marginTop:4},pay:{backgroundColor:"#16daca",paddingVertical:18,paddingHorizontal:20,borderRadius:14},payText:{fontSize:18,fontWeight:"900"}});
